const fs = require('fs');
const session = 'C:/Users/asus/.codex/sessions/2026/04/10/rollout-2026-04-10T09-52-55-019d762a-4871-7111-be00-32147c7cbb36.jsonl';
const stat = fs.statSync(session);
console.log('size', stat.size);
const chunk = 45 * 1024 * 1024;
const start = Math.max(0, stat.size - chunk);
const len = stat.size - start;
const fd = fs.openSync(session, 'r');
const b = Buffer.alloc(len);
const r = fs.readSync(fd, b, 0, len, start);
fs.closeSync(fd);
console.log('read', r);
const text = b.toString('utf8');
console.log('text len', text.length);
console.log('contains', text.includes('inlocuieste imagineile cu destination'));
