using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TravelBackend.DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class InitialUserCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Users" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FirstName" character varying(30) NOT NULL,
                    "LastName" character varying(30) NOT NULL,
                    "UserName" character varying(30) NOT NULL,
                    "Email" character varying(60) NOT NULL,
                    "Password" character varying(48) NOT NULL,
                    "Phone" character varying(12) NOT NULL,
                    "Role" integer NOT NULL,
                    "RegisteredOn" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "Users";""");
        }
    }
}
