using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TravelBackend.DataAccess.Migrations.Travel
{
    /// <inheritdoc />
    public partial class InitialTravelCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Bookings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" integer NOT NULL,
                    "ListingType" character varying(30) NOT NULL,
                    "ListingId" integer NOT NULL,
                    "CheckIn" timestamp with time zone NOT NULL,
                    "CheckOut" timestamp with time zone NOT NULL,
                    "Guests" integer NOT NULL,
                    "TotalPrice" numeric(18,2) NOT NULL,
                    "Status" integer NOT NULL,
                    "IsDeleted" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Destinations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(80) NOT NULL,
                    "Country" character varying(80) NOT NULL,
                    "Description" character varying(500) NOT NULL,
                    "ImageUrl" character varying(300) NOT NULL,
                    "IsDeleted" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "PK_Destinations" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Favorites" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" integer NOT NULL,
                    "ListingType" character varying(30) NOT NULL,
                    "ListingId" integer NOT NULL,
                    "IsDeleted" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Hotels" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(100) NOT NULL,
                    "Description" character varying(500) NOT NULL,
                    "DestinationId" integer NOT NULL,
                    "PricePerNight" numeric(18,2) NOT NULL,
                    "Rating" double precision NOT NULL,
                    "ImageUrl" character varying(300) NOT NULL,
                    "IsDeleted" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "PK_Hotels" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "PlannerTrips" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" integer NOT NULL,
                    "DestinationId" integer NOT NULL,
                    "Title" character varying(100) NOT NULL,
                    "StartDate" timestamp with time zone NOT NULL,
                    "EndDate" timestamp with time zone NOT NULL,
                    "Notes" character varying(1000) NOT NULL,
                    "IsDeleted" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "PK_PlannerTrips" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Rentals" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(100) NOT NULL,
                    "RentalType" character varying(60) NOT NULL,
                    "Description" character varying(500) NOT NULL,
                    "DestinationId" integer NOT NULL,
                    "PricePerDay" numeric(18,2) NOT NULL,
                    "ImageUrl" character varying(300) NOT NULL,
                    "IsDeleted" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "PK_Rentals" PRIMARY KEY ("Id")
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "Bookings";
                DROP TABLE IF EXISTS "Destinations";
                DROP TABLE IF EXISTS "Favorites";
                DROP TABLE IF EXISTS "Hotels";
                DROP TABLE IF EXISTS "PlannerTrips";
                DROP TABLE IF EXISTS "Rentals";
                """);
        }
    }
}
